name: Build and Deploy Hugo to ruqinga.github.io

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.122.0
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to ruqinga.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: ruqinga/ruqinga.github.io
          publish_branch: main   # 或者 gh-pages
          publish_dir: ./public
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
